#!/usr/bin/env ruby
# Just run as a cron job once per day

require 'pg'
require 'json'
require 'net/http'
require 'peeps-config.rb'

db = PG::Connection.new(dbname: 'd50b', user: 'd50b')

uri = URI('http://openexchangerates.org/api/latest.json?app_id=' + OPENEXCHANGERATES)
js = Net::HTTP.get(uri)

db.exec_params("SELECT * FROM core.update_currency_rates($1)", [js])
