#!/usr/bin/env ruby
exit unless 'sivers.org' == %x{hostname}.strip
require 'pg'
require 'json'
require 'my_mail'
require 'peeps-config.rb'

db = PG::Connection.new(dbname: 'd50b', user: 'd50b')

%w(derek@sivers we@woodegg).each do |profile|
	puts "\n\n##### #{profile}"
	MyMail::import(profile, PROFILES[profile][:pop3], db)
end

