#!/usr/bin/env ruby
exit unless 'sivers.org' == %x{hostname}.strip
# only one instance of this Ruby script running at one time:
exit unless File.new(__FILE__).flock(File::LOCK_EX | File::LOCK_NB)
require 'pg'
require 'json'
require 'my_mail'
require 'peeps-config.rb'

db = PG::Connection.new(dbname: 'd50b', user: 'd50b')

res = db.exec('SELECT js FROM peeps.queued_emails()')
emails = JSON.parse(res[0]['js'], symbolize_names: true)

emails.each do |e|
	if MyMail::send(e, PROFILES[e[:profile]][:smtp])
		db.exec_params('SELECT * FROM peeps.email_is_sent($1)', [e[:id]])
	end
end

